-- MySQL Database --
CREATE DATABASE vendas;

CREATE TABLE cliente (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    CPF CHAR(11) UNIQUE NOT NULL,
    NOME VARCHAR(100) NOT NULL
);

CREATE TABLE produto (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(200) NOT NULL,
    PRECO_UNITARIO NUMERIC(20, 2) NOT NULL
);

CREATE TABLE pedido (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    CLIENTE_ID INTEGER REFERENCES CLIENTE (ID),
    DATA_PEDIDO TIMESTAMP,
    STATUS VARCHAR(20) NOT NULL,
    TOTAL NUMERIC(20,2) NOT NULL
);

CREATE TABLE item_pedido (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    PEDIDO_ID INTEGER REFERENCES PEDIDO (ID),
    PRODUTO_ID INTEGER REFERENCES PRODUTO (ID),
    QUANTIDADE INTEGER NOT NULL
);

CREATE TABLE usuario (
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  LOGIN VARCHAR(80) UNIQUE NOT NULL,
  SENHA VARCHAR(255) NOT NULL,
  ADMIN BOOL DEFAULT FALSE
);
